### PR TITLE
Update examples/pennylane_run_variational_classifier.py.

### PR DESCRIPTION
**Pull request by israelferrazaraujo**
**Context:**
In this particular case the modification is mathematically irrelevant but necessary to be in accordance with that shown in equation (8) of the reference `Möttönen, et al. (2004) <https://arxiv.org/abs/quant-ph/0407010> `.

**Description of the Change:**
The square is positioned within the square root.

**Benefits:**
Avoid confusion in future cases where this detail is mathematically relevant (when there are more summation terms).

**Possible Drawbacks:**
None.

**Related GitHub Issues:**
None.

### CODE REVIEW

**Comment by josh146** [comment]
@mariaschuld, does this also need to be updated over on https://github.com/XanaduAI/qml?

**Comment by mariaschuld** [comment]
Oh, are we keeping separate copies of the examples? If so, then maybe good to have it there as well. On my list.

**Comment by co9olguy** [comment]
The examples here are included in the library when people download, but the online examples are now in the other repo

**Comment by josh146** [comment]
I'm thinking, just for ease of maintenance, that we delete the `pennylane/examples` folder, and instead add a section to the readme pointing users over to the QML website/repo.

Or, we can have an `examples` folder that points to `qml/beginners` and `qml/implementations` via git submodules.

**Comment by co9olguy** [comment]
first one probably best

**Pull request merged**
