### PR TITLE
Replace device.supported with separate methods for ops and expvals

### PR DESCRIPTION
**Pull request by johannesjmeyer**
**Description of the Change:**
The method device.supported was replace with the two separate methods
device.supports_operation and device.supports_expectation to get around
the problem that there are operations and expectations with the same
name.

Unit tests where added for the new methods and the unit test for the
old method removed. Additionally, unit tests for default.qubit and
default.gaussian had to be changed. The description in the documentation
was also altered to reflect the new methods.

**Benefits:**
The erroneous behaviour of `device.supported` is replaced with the clear `device.supports_operation` and `device.supports_expectation`.

**Possible Drawbacks:**
Compatibility will be broken because `device.supported` is removed.

**Related GitHub Issues:**
#205 

## PS
I did _not_ go for the variant 
```python
import pennylane as qml

mydevice.supports(qml.PauliX)
mydevice.supports(qml.expval.PauliX)
```
(for now), because this would mean a deeper change in multiple locations that would have to be discussed first. Right now, strings are used all over the place to identify gates (which is fine), and not using them only in `device.supports` would be inconsistent.

#### PPS
There was one test that did not run which was unrelated to my changes and possibly due to the fact that I'm on a Windows machine. 
```
  File "D:\dev\xanadu\pennylane\tests\test_default_qubit.py", line 769, in test_supported_observables
    self.assertAllEqual(circuit(H), reference(H))
  File "D:\dev\xanadu\pennylane\tests\defaults.py", line 78, in assertAllEqual
    return self.assertAllAlmostEqual(first, second, delta=0.0, msg=msg)
  File "D:\dev\xanadu\pennylane\tests\defaults.py", line 72, in assertAllAlmostEqual
    raise self.failureException(msg)
AssertionError: 0.9256130778506405 != (0.9256130778506405+2.7755575615628914e-17j) within 0.0 delta
```
I think it would be appropriate to change this to assertAllAlmostEqual, wouldn't it? Running comparisons on floats with 0.0 tolerance seems to be quite strict.

### CODE REVIEW

**Comment by josh146** [comment]
Thanks for the pull request @johannesjmeyer! Everything looks great, and all the continuous integration checks are passing. We'll go through it and send back our review hopefully early next week.

**Comment by co9olguy** [comment]
Looks good @johannesjmeyer, thanks!

**Comment by co9olguy** [comment]
btw thanks for spotting the failure in the test. The delta should definitely not be 0.0 there

**Comment by co9olguy** [comment]
Note: with this recent refactor of `expvals` (#232), we'll have to revisit this PR at some point in the near future

**Comment by johannesjmeyer** [comment]
Ok, I had a look and I like #232 very much! I think the only thing that is required in this specific PR is to change `supports_expectation` to `supports_observable`. But for this to be coherent one would also have to change the name of `Device.expectations` to `Device.observables` which in turn would break existing plugins (correcting this would be a small change though).

**Comment by josh146** [comment]
Hi @johannesjmeyer, I've already made the breaking change `Device.expectations` to `Device.observables` 🙂 Just in the process of updating all the plugins now

**Comment by johannesjmeyer** [comment]
Good, then I'll just rename it!

**Comment by co9olguy** [comment]
@johannesjmeyer is this ready for re-review in light of #232 being finalized and merged?

**Comment by johannesjmeyer** [comment]
> @johannesjmeyer is this ready for re-review in light of #232 being finalized and merged?

No. I suggest we merge the other PRs first and then I'll redo this change from the master branch. This will probably take less time than resolving the merge conflicts of this PR because the change is really straightforward.

**Comment by johannesjmeyer** [comment]
Closing this due to newer pull request on the same topic.

**Pull request closed without merging**
