### PR TITLE
Adding missing modules to documentation API

### PR DESCRIPTION
**Pull request by josh146**
**Description of the Change:**

* Adds the following missing modules back into the documentation: `utils`, `variable`, `interfaces`, `operation`.

* This is done in as automatic way as possible, using `autosummary` and `automodapi`,

* Warnings are added to the top of each 'low level' module, warning the user and directing them to the equivalent 'high level' place.

* One method from the CV mixin class has been moved to CVOperation, as it uses an attribute that only exists in CVOperation and was causing Sphinx to crash.

**Benefits:** API section is now ~complete.

**Possible Drawbacks:**

* Some things are still missing; e.g. the named tuples in the `circuit_graph` module are not imported top-level, but `CircuitGraph` is. Where to put the named tuples?

* Should we have a separate section in the TOC for the low-level classes?

**Related GitHub Issues:** n/a

### CODE REVIEW

**Comment by josh146** [comment]
Rendered version here: https://pennylane.readthedocs.io/en/add_missing_modules/

**Comment by josh146** [comment]
Note: I've just created another branch, where the API documentation is fully automated, just using calls to `automodapi`. This branch is available here, https://github.com/XanaduAI/pennylane/compare/more_automatic, with rendered docs here: https://pennylane.readthedocs.io/en/more_automatic/

**Comment by mariaschuld** [comment]
One thing that we have to decide: what is a module? Is it a set of functionalities a user can use? Or is it any file that contains PL code?

With the last version I went with the strict approach (suggested by @co9olguy), and a user does never touch the utilities...Shall we really report on every detail in the API?

**Comment by josh146** [comment]
> Or is it any file that contains PL code?

My feeling is the biggest issue with the previous PL documentation was the navigation --- it was confusing (to users and developers) where to find things, as the module docstrings were used for both introductory details and low-level code details.

With the new structure, there are a lot of advantages (it is really really good, kudos @mariaschuld):

1. The introductory material on how to use PennyLane is separate from the module docstrings, and in a easy to find top section of the TOC

2. Now that each function/class/etc. has its own page, it is much easier to link to, and users won't get confused with information overload.

3. We can focus on making the API section what it should have been all along - an entry point for developers needing to understand the code. So we _should_ have all modules documented here, even low level ones (developers are users too :slightly_smiling_face: etc. ), and at the same time be more confident that users will be much less likely to end up here (much like how in the NumPy docs, it is more difficult to end up on a page like https://docs.scipy.org/doc/numpy/reference/c-api.html by accident).

**Comment by co9olguy** [comment]
Looks good. I certainly favour the more maintainable approach. I think losing the nice sort order is not a problem, since we have a more curated presentation under "Using PennyLane". Basically, we can think of anything that is curated/highlighted/manual will likely go under "Using PennyLane", and anything that is more about the details of the code can be autogenerated from module docstrings.

I noticed only two differences between the branches:
- `qml` page of `API` looks substantially different for the `more_automatic` branch
- `qml.templates` page slightly different for `add_missing_modules` branch than for `more_automatic` branch (second one has table, looks better, consistent with other pages)

Regarding what we should expose: I'm in favour of exposing all public classes/functions under API, and leaving private classes/functions to the source code

**Comment by co9olguy** [comment]
Also, let's make it a rule to avoid a TOC that is larger than one page. The current amount of content seems to be in the goldilocks zone. If we start having significantly more, we can revise

**Comment by josh146** [comment]
> Also, let's make it a rule to avoid a TOC that is larger than one page. The current amount of content seems to be in the goldilocks zone. If we start having significantly more, we can revise

Agree.

> qml page of API looks substantially different for the more_automatic branch

In `add_missing_modules`, this is remained unchanged from master (the custom page written by @mariaschuld).

In `more_automatic`, I have replaced the entire file with a single call to `.. automodapi:: pennylane`, which automatically extracts and lists all functions, at the expense of the organization.

I agree --- since we have a curated organization in 'Using PennyLane', I don't think it's needed here.

> qml.templates page slightly different for add_missing_modules branch than for more_automatic branch (second one has table, looks better, consistent with other pages)

Same reason as above --- a custom written landing page by @mariaschuld has been replaced with a single `.. autosummary::`.

> I'm in favour of exposing all public classes/functions under API, and leaving private classes/functions to the source code

By default, `automodapi` and `autosummary` do not expose private functions, so that works well.

**Comment by josh146** [comment]
> Note: The qml.init module in the automatic version does not do autoapi, but uses the handwritten structure. Is that intended? I would rather make it consistent to the other modules (i.e. the header is "Functions" and then all functions are listed).

I missed that one! Good catch.

**Pull request merged**
