### PR TITLE
Unset attribute in test

### PR DESCRIPTION
**Pull request by mariaschuld**
**Context:**

We had a very hard-to-track bug in the tests: When moving a specific test into a subfolder, it would suddenly fail. What happens is that moving the test changes the execution order of tests. As a consequence, a certain troublesome qnode test gets executed first. In it, a device class attribute gets assigned and screws up the later test.

**Description of the Change:**

Unset value of attribute in test that causes trouble.

**Benefits:** Prevents future issues where this test interferes with others.

### CODE REVIEW

**Comment by mariaschuld** [comment]
@smite, tagging you here in case you wrote the test...

**Comment by mariaschuld** [comment]
Of course, one could turn all class attributes into instance attributes (see for example [here](https://dzone.com/articles/python-class-attributes-vs-instance-attributes) for explanation).

But I think this is not necessary. Users who happen to set class attributes such as ``Device._capabilities`` should know what they are doing, because you need to dig deep into the code to even find them, _and_ they are marked as private. 

We should simply be unset them if this is used in tests.

**Comment by josh146** [comment]
I agree - this is an issue/bug with the tests not doing a proper tear down, rather than an issue with the codebase.

**Comment by co9olguy** [comment]
Not a big fan of using class attributes for exactly this reason

**Comment by josh146** [comment]
It definitely makes sense in this case (device defaults) since we are storing class constants and default class data. In addition, these values are static and are not modified or changed in any part of the logic or source code. I think this underlies an issue that is probably systematic across our tests, we should be better at doing test teardown in general.

The main 'gotcha' with class attributes come when they _are_ modified during program execution to keep track of class states, c.f. the variable class. This also has a place (same with class methods and static methods), but can lead to issues of unintentionally changing the state.

**Comment by mariaschuld** [comment]
Thanks @josh146 , is this what you have in mind? I don't know if the assert statements need to be in the monkeypatch scope...

**Pull request merged**
