### PR TITLE
 Fix#304 - Add sample to explicit members in automodule 

### PR DESCRIPTION
**Pull request by mariaschuld**
This PR addresses Issue #304.

It adds the "sample" function to the explicit list of functions generated by the automodule directive for pennylane.measure.

### CODE REVIEW

**Comment by co9olguy** [comment]
Is this showing up in docs? I'm seeing `sample` under `Summary`, but not under `Code details`

[https://pennylane.readthedocs.io/en/latest/code/measure.html](https://pennylane.readthedocs.io/en/latest/code/measure.html)

**Comment by josh146** [comment]
Looking on RTDs, this is because the latest master branch docs failed to build

**Comment by josh146** [comment]
Should be as easy as restarting the build

**Comment by josh146** [comment]
This is fixed as per 87c69b43.

**Pull request merged**
