### PR TITLE
Fix Issue 532 - Bug in RandomLayers

### LINKED ISSUE #532: RandomLayers does not work with the Qiskit plugin as NumPy native integers are passed as wires instead of Python ints
#### Issue description

* *Expected behavior:*

No problem with using `RandomLayers` with the Qiskit plugin.

* *Actual behavior:*

As `RandomLayers` uses `numpy` specific functions to generate `wires`, `numpy` native integers are returned as `wires` instead of values of type `int`. This results in a Qiskit error when using devices from the Qiskit plugin as per the following known bug and open issue:
https://github.com/Qiskit/qiskit-terra/issues/3929

* *Reproduces how often:*

Each time `RandomLayers` is used with the Qiskit plugin.

* *System information:*

```
Name: PennyLane
Version: 0.9.0.dev0
Summary: PennyLane is a Python quantum machine learning library by Xanadu Inc.
Home-page: https://github.com/XanaduAI/pennylane
Author: None
Author-email: None
License: Apache License 2.0
Location: /xanadu/pennylane
Requires: numpy, scipy, networkx, autograd, toml, appdirs, semantic-version
Required-by: 
Platform info:           Linux-4.19.11-041911-generic-x86_64-with-debian-buster-sid
Python version:          3.7.6
Numpy version:           1.17.4
Scipy version:           1.3.2
Installed devices:
- default.gaussian (PennyLane-0.9.0.dev0)
- default.qubit (PennyLane-0.9.0.dev0)
- default.tensor (PennyLane-0.9.0.dev0)
- default.tensor.tf (PennyLane-0.9.0.dev0)
- strawberryfields.fock (PennyLane-SF-0.8.0)
- strawberryfields.gaussian (PennyLane-SF-0.8.0)
- qiskit.aer (PennyLane-qiskit-0.8.0)
- qiskit.basicaer (PennyLane-qiskit-0.8.0)
- qiskit.ibmq (PennyLane-qiskit-0.8.0)
- forest.numpy_wavefunction (PennyLane-Forest-0.8.0)
- forest.qpu (PennyLane-Forest-0.8.0)
- forest.qvm (PennyLane-Forest-0.8.0)
- forest.wavefunction (PennyLane-Forest-0.8.0)
- projectq.classical (PennyLane-PQ-0.7.0.dev0)
- projectq.ibm (PennyLane-PQ-0.7.0.dev0)
- projectq.simulator (PennyLane-PQ-0.7.0.dev0)
- microsoft.QuantumSimulator (PennyLane-qsharp-0.6.0)
- cirq.simulator (PennyLane-Cirq-0.8.0)
```

#### Source code and tracebacks

Code to reproduce this problem:
```python
import pennylane as qml
from pennylane.templates.layers import RandomLayers
from pennylane.init import random_layers_uniform
import numpy as np


num_qubits = 5

dev = qml.device('qiskit.aer',wires=num_qubits)
conv_params = random_layers_uniform(n_layers=3, n_wires=num_qubits, seed=2)

@qml.qnode(dev)
def circuit(weights=None):
    RandomLayers(weights=weights, wires=list(range(num_qubits)))
    return qml.expval(qml.PauliZ(0))

circuit(weights=conv_params)
```

Traceback:
```python
~/anaconda3/lib/python3.7/site-packages/qiskit/circuit/register.py in __getitem__(self, key)
     88         """
     89         if not isinstance(key, (int, slice, list)):
---> 90             raise CircuitError("expected integer or slice index into register")
     91         if isinstance(key, slice):
     92             return self._bits[key]
CircuitError: 'expected integer or slice index into register'
```

**Note**: a quick fix is available on the `wires_to_int` branch.

#### Additional information

Things to consider:
* this particular case might be solved in Qiskit with a next release;
* further templates might include similar logic for `wires`.

**Fruit for thought in the long run:** it could be a good idea in general, to place a sort of "wire type" modifying logic in PennyLane, such that "from a given point" in the line of execution, it would be guaranteed, that all `wires` are of type `int` under the hood.

This would allow:
* **validation** for wire types and a possibly needed **conversion** of `wires` to take place only at one place in the entire codebase
* any operation (such as `RandomLayers`) to not need to contain logic on conversion, checking validity, etc.

### PR DESCRIPTION
**Pull request by mariaschuld**
**Context:**

Fix for Issue #532: The RandomLayers template used numpy's ``random.choice`` function to select wires. This function however returns ``numpy`` objects, which some devices - like qiskit - can't deal with.

Note that with our planned improved wire management this bug would not appear.

**Description of the Change:**

Convert wires back to ``int``.

**Related GitHub Issues:**

Fixes #532

### CODE REVIEW

**Comment by mariaschuld** [comment]
A question raised by the bug is whether we must test all templates with all plugins.

**Comment by mariaschuld** [comment]
I think we should leave this, and then revisit with the new wire management. Thanks for the review!

**Comment by mariaschuld** [comment]
@josh146 sorry to rope you in - codecov is complaining, but a) there is an _increase_ in coverage and b) only a few lines were added to a covered code section...shall we overwrite?

**Comment by josh146** [comment]
Looks like codecov is at fault here, happy to merge this one in once it looks good from your end!

**Pull request merged**
