### PR TITLE
fix sign in gradient recipe and fix code snippet in measure.py

### PR DESCRIPTION
**Pull request by AroosaIjaz**
**Description of the Change:**

Fixed the sign of the gradient recipe for RX, RY and RZ.

### CODE REVIEW

**Comment by co9olguy** [comment]
@AroosaIjaz I notice the same typo for a couple other gates. Can you update those in this PR as well?

**Comment by AroosaIjaz** [comment]
Sure, let me check.

**Comment by AroosaIjaz** [comment]
This should be ready to merge now.

**Comment by co9olguy** [comment]
Thanks @AroosaIjaz. Closes #249

**Pull request merged**
