### PR TITLE
Make quick reference a top level section in docs

### PR DESCRIPTION
**Pull request by mariaschuld**
This PR moves the "Quick Reference" to the first level of sections and splits the corresponding rst file into several files.

This addresses the following two issues: 
- Docs look bare after outsourcing the background sections
- Quick reference should have first order access

### CODE REVIEW

**Comment by josh146** [comment]
This is great, and really fast, thanks Maria!

One question though - what distinguishes the 'quick reference' section from the 'using PennyLane' section - aren't they the same? Like, why have Interfaces in 'Using', but 'Operations' (which are probably same importance level) in quick reference?

On a completely different tangent, this is something I wondered when going through your previous PR. How come 'Quantum Circuit' rather than 'Quantum Node'?

**Comment by mariaschuld** [comment]
Quantum circuit just because people who look in the intro section don't necessarily know what a quantum node is, while circuit is common language.

Quick reference contains lists of PL building blocks that link to API, that any advanced user may need to look up what's currently available. "Using Pennylane" contains introductions and explanations for beginners...but if it's odd to you, maybe there is a better way to organise? 

Feel free to ignore this PR if it is not improving the docs...

**Comment by josh146** [comment]
> Quantum circuit just because people who look in the intro section don't necessarily know what a quantum node is, while circuit is common language.

:thumb:

> Quick reference contains lists of PL building blocks that link to API, that any advanced user may need to look up what's currently available. "Using Pennylane" contains introductions and explanations for beginners...but if it's odd to you, maybe there is a better way to organise?

It does feel a bit odd, but mostly because it seems very similar to the 'API/qml' page. At the same time, I'm not really sure the best way to improve it.

Maybe it should be fleshed out with more (brief) examples like the Using PennyLane section? Something that comes to mind is tensor observables. This pattern won't show up in the API, but could be explained with brief examples in the 'Operations' section.

Another thing that won't show up in the API are the options for default qubit and default gaussian (i.e., going through details like number of shots, the analytic argument, etc).

Let me think about this a bit more.

**Comment by co9olguy** [comment]
Just getting a look at this now. I agree with @josh146 that "Quick Reference" seems to be out of place as a separate heading. 

I had pictured that the items that were previously hidden within the "Quick Reference" page (ops, measurements, optimizers, templates, configuration) should be present on the TOC. But I think these all fit easily under "Using PennyLane", since that section gives a users an overview of all user-facing functionality.

**Comment by co9olguy** [comment]
I updated to put everything all the core stuff under one heading. I think it looks good (TOC is not bare), nothing is hidden away, and each page under the "Using PennyLane" fits naturally

**Comment by co9olguy** [comment]
I still have to do more careful review, but this looks great; thanks @mariaschuld!

**Comment by co9olguy** [comment]
Going to merge this, because I'm happy with the look. We'll go through individual pages 1-by-1 and polish them as separate PRs

**Pull request merged**
